events {
}

http {
    upstream api {
        server api-java1:8080;
        server api-java2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api;
        }
    }
}